# Generated by Django 4.0.4 on 2022-05-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0002_vaitro_user_vai_tro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vai_tro',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='quanly.vaitro'),
        ),
    ]
