# Generated by Django 4.0.4 on 2022-05-16 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0003_alter_user_vai_tro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='so_dt',
            field=models.CharField(default=1, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='vai_tro',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.CASCADE, to='quanly.vaitro'),
        ),
    ]
