# Generated by Django 4.0.4 on 2022-05-16 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0004_alter_user_so_dt_alter_user_vai_tro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vai_tro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quanly.vaitro'),
        ),
    ]
